// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV8CBWi0JZz2Z1-EFhSWM2a8gHHnXJLZE',
    appId: '1:404731605087:web:62f40bb2ac7d1039b06bea',
    messagingSenderId: '404731605087',
    projectId: 'renalbites',
    authDomain: 'renalbites.firebaseapp.com',
    storageBucket: 'renalbites.firebasestorage.app',
    measurementId: 'G-Q1BE4Y8BWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuM7rDTDdobZTYbNc4oe1UH1mu1eZ__rM',
    appId: '1:404731605087:android:614d85a7bc0bed6fb06bea',
    messagingSenderId: '404731605087',
    projectId: 'renalbites',
    storageBucket: 'renalbites.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeijuO-PLaI1NWHAYWzXxf4sJNVTjEv8U',
    appId: '1:404731605087:ios:c4fae3f24e3adbc6b06bea',
    messagingSenderId: '404731605087',
    projectId: 'renalbites',
    storageBucket: 'renalbites.firebasestorage.app',
    iosBundleId: 'com.example.renalbites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeijuO-PLaI1NWHAYWzXxf4sJNVTjEv8U',
    appId: '1:404731605087:ios:c4fae3f24e3adbc6b06bea',
    messagingSenderId: '404731605087',
    projectId: 'renalbites',
    storageBucket: 'renalbites.firebasestorage.app',
    iosBundleId: 'com.example.renalbites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV8CBWi0JZz2Z1-EFhSWM2a8gHHnXJLZE',
    appId: '1:404731605087:web:31db29b4e3805623b06bea',
    messagingSenderId: '404731605087',
    projectId: 'renalbites',
    authDomain: 'renalbites.firebaseapp.com',
    storageBucket: 'renalbites.firebasestorage.app',
    measurementId: 'G-RG1W2DCYQ0',
  );
}
